version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dating-question-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dating_question
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
